# Generated by Django 6.0.1 on 2026-01-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('indirizzo', models.CharField(max_length=100)),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venditore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=10, unique=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
