# Generated by Django 6.0.1 on 2026-01-19 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('immatricolazione', models.DateField()),
                ('categoria', models.CharField(choices=[('suv', 'SUV'), ('berlina', 'Berlina'), ('station_wagon', 'Station Wagon'), ('coupe', 'Coupé'), ('monovolume', 'Monovolume'), ('fuoristrada', 'Fuoristrada'), ('cabrio', 'Cabrio'), ('pick_up', 'Pick-up')], max_length=20)),
                ('condizioni', models.CharField(choices=[('nuova', 'Nuova'), ('usata', 'Usata'), ('km0', 'Chilometro Zero')], max_length=5)),
                ('alimentazione', models.CharField(choices=[('benzina', 'Benzina'), ('diesel', 'Diesel'), ('elettrica', 'Elettrica'), ('ibrida', 'Ibrida'), ('gpl', 'GPL'), ('metano', 'Metano')], max_length=9)),
                ('chilometraggio', models.IntegerField()),
                ('tipo_cambio', models.CharField(choices=[('manuale', 'Manuale'), ('automatico', 'Automatico'), ('semi-automatico', 'Semi-automatico')], max_length=15)),
                ('potenza', models.CharField(max_length=50)),
                ('classe_emissioni', models.CharField(choices=[('euro6d', 'Euro 6d'), ('euro6', 'Euro 6'), ('euro5', 'Euro 5'), ('euro4', 'Euro 4'), ('euro3', 'Euro 3')], max_length=6)),
                ('numero_porte', models.IntegerField()),
                ('sensori_parcheggio', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('frenata_emergenza', models.BooleanField(default=False)),
                ('start_and_stop', models.BooleanField(default=False)),
                ('incidenti_precedenti', models.BooleanField(default=False)),
                ('disponibilita', models.BooleanField(default=False)),
                ('luogo_veicolo', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venditore')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stato_ordine', models.CharField(choices=[('in_attesa_pagamento', 'In attesa pagamento'), ('pagato', 'Pagato'), ('in_consegna', 'In consegna'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='in_attesa_pagamento', max_length=19)),
                ('pagamento', models.CharField(choices=[('carta_di_credito', 'Carta di credito'), ('bonifico_bancario', 'Bonifico bancario'), ('leasing', 'Leasing'), ('pagamento_fisico', 'Pagamento fisico')], max_length=17)),
                ('indirizzo_consegna', models.CharField(max_length=100)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessionario_app.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessionario_app.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'auto')},
            },
        ),
    ]
