# Generated by Django 6.0.1 on 2026-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='auto',
            name='posti',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
