# Generated by Django 6.0.1 on 2026-01-21 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0002_auto_foto_auto_posti'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
