# Generated by Django 6.0.1 on 2026-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0003_auto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='disponibilita',
            field=models.BooleanField(default=True),
        ),
    ]
