# Generated by Django 6.0.1 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0004_alter_auto_disponibilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='auto/video/'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='auto/foto/'),
        ),
    ]
