# Generated by Django 6.0.1 on 2026-02-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0005_auto_video_alter_auto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='foto',
        ),
        migrations.CreateModel(
            name='FotoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='auto/foto/')),
                ('is_principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(default=0)),
                ('caricata_il', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='concessionario_app.auto')),
            ],
            options={
                'ordering': ['-is_principale', 'ordine'],
            },
        ),
    ]
