# Generated by Django 6.0.1 on 2026-02-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0006_remove_auto_foto_fotoauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('messaggio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='concessionario_app.auto')),
            ],
        ),
    ]
