# Generated by Django 6.0.1 on 2026-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0007_richiestainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestainfo',
            name='gestita',
            field=models.BooleanField(default=False),
        ),
    ]
