# Generated by Django 6.0.1 on 2026-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionario_app', '0008_richiestainfo_gestita'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='auto/loghi/')),
            ],
            options={
                'verbose_name_plural': 'Loghi Marche',
                'ordering': ['marca'],
            },
        ),
    ]
